### ISSUE TITLE
Summary Geographies missing on "Trip Trends" tab

### ISSUE THREAD

**Issue by jlillywhiteMAG** [WFRCAnalytics/vizTool#26]
The trip trends chart includes a "summary geographies" dropdown, but the only option to select is the Wasatch Front Model Area. I assume the intent was to provide other options there. 
![Screenshot 2024-10-29 124842](https://github.com/user-attachments/assets/344fd143-fbc4-4c88-910f-bef070c315b9)

**Comment by bhereth** [comment]
This is actually due to the shares report in the TDM being for the entire model and not separable by geography, since trips cross geographies. The drop down may be misleading, thinking there is an ability to select different geographies. Perhaps we hide it. The best proxy to get transit data by geography would be the Transit Stops trends in the Roads and Transit section.
